name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Frontend Dependencies
      run: npm ci
    
    - name: Lint Frontend
      run: npm run lint --max-warnings 100 || true
      continue-on-error: true
    
    - name: Type Check Frontend
      run: npm run type-check
      continue-on-error: true
    
    - name: Build Frontend
      run: npm run build
    
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm ci
    
    - name: Lint Backend
      run: |
        cd backend
        npm run lint --max-warnings 100 || true
      continue-on-error: true
    
    - name: Type Check Backend
      run: |
        cd backend
        npm run type-check
      continue-on-error: true
    
    - name: Build Backend
      run: |
        cd backend
        npm run build

  test:
    runs-on: ubuntu-latest
    needs: lint-and-test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Dependencies
      run: |
        npm ci
        cd backend && npm ci
    
    - name: Run Frontend Tests
      run: npm test -- --passWithNoTests
      continue-on-error: true
    
    - name: Run Backend Tests
      run: |
        cd backend
        npm test -- --passWithNoTests
      continue-on-error: true

  security:
    runs-on: ubuntu-latest
    needs: [lint-and-test, test]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Dependencies
      run: |
        npm ci
        cd backend && npm ci
    
    - name: Run Security Audit
      run: |
        npm audit --audit-level moderate || true
        cd backend && npm audit --audit-level moderate || true
